### ISSUE TITLE
getRequestToken method is throwing error

### ISSUE THREAD

**Issue by brianbier** [shalvah/twittersignin#7]
Hi, I've followed the steps in the read and added my access tokens and secrets but when I try to get the token it throws the following error: I know the token is valid because I tested using postman. Is there anything i may be missing?

```
err Error: Invalid or expired token.
    at Object.exports.makeTwitError (/server/node_modules/twit/lib/helpers.js:74:13)
    at Request.onRequestEnd (server/node_modules/twittersignin/index.js:55:41)
    at Request.emit (events.js:326:22)
    at Gunzip.<anonymous> (/server/node_modules/twittersignin/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:420:28)
    at Gunzip.emit (events.js:314:20)
    at endReadableNT (_stream_readable.js:1244:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 89,
  allErrors: [ { code: 89, message: 'Invalid or expired token.' } ],
  twitterReply: { errors: [ [Object] ] },
  statusCode: 401
}
```

My Code:

```
router.get("/twitter", async (req,res) =>{
  try {

    const response = await twitterSignIn.getRequestToken()

  } catch (error) {
    console.log('err', error);
  }
console.log('im in here login')
  res.json({
    message: "user updated"
  });
});
```

**Comment by shalvah** [comment]
Hey, I don't think this is an error from the library. I use it everyday without problems. There are a number of different reasons why you might have gotten that response. See some here: https://stackoverflow.com/questions/17636701/twitter-api-reasons-for-invalid-or-expired-token
